### ISSUE TITLE
Web GL creates random margin space between candles

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1623] opened 2020-09-16 02:00 UTC
Not sure if I missed something, but two charts using the same code and the same static JSON data look differently, specifically the **space between candles on the Web GL chart is different for some candles**. In another project, I faced an issue when Web GL was drawing some of the new candles on top of the previous ones. Couldn't understand what's wrong, because everything was intact, so created a simpler example below. Another project was using `linear` scales for X and Y without `extent`, a simple example below uses the `date` scale for X axis. Maybe some scaling issue? 

**Canvas**
https://codepen.io/artemiusgreat/pen/VwaxGKP

**Web GL**
https://codepen.io/artemiusgreat/pen/WNwKMom

**The screenshot of the Web GL issue**
https://imgur.com/a/FE4upzb

The only difference between them is that I replaced `webgl` calls with relevant `canvas` counterparts. For some reason, Web GL not just decreases the space between candles, it actually places candles against the wrong mark on the scale. For example, if the candle has time property 7:05, on the canvas chart it appears in the right place, but on webgl it may be shifted to 7:07.

**Comment by chrisprice** [comment] 2020-09-16 09:38
This is a duplicate of #1563. WebGL only allows float32 precision so looking at a small range of time offset by a large amount from the epoch will introduce visible errors. The PR in the issue attempts to resolve this in the common case by moving the epoch for timestamps to the timestamp when the script loaded. In your case the values are from a number of years ago, so you might want to change their epoch to explicitly (using a similar technique to that used in the PR).

`1138752000000 === Wed Feb 01 2006 00:00:00 GMT+0000 (Greenwich Mean Time)`

**Closed as completed** 2020-09-16 09:38 UTC
