### ISSUE TITLE
How to use d3fc with React Typescript Project

### ISSUE THREAD

**Issue by etechprathmesh** [d3fc/d3fc#1669] opened 2021-02-18 06:01 UTC
Hi,

I want to use D3FC in React Typescript project. But I am not able to create simple LineChart.  

I have installed "d3fc" via  npm install d3fc but getting following Error while using in tsx file (import d3fc from 'd3fc')
Error: Could not find a declaration file for module 'd3fc'. 'e:/d3fc/d3fc1/node_modules/d3fc/build/d3fc.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/d3fc` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3fc';`ts(7016)

Kindly help on how to use d3fc in React-TypeScript Appliction.

Help in this regard will be highly appreciated.

Regards,
Prathmesh Shah

**Comment by etechprathmesh** [comment] 2021-02-19 09:55
Kindly reply... How to use d3fc with React Typescript.  Import statement is not working

**Comment by etechprathmesh** [comment] 2021-02-20 17:30
Waiting for your support.

**Comment by chrisprice** [comment] 2021-02-20 20:02
That's a TypeScript error telling you there's no declaration file for this library.

If you're looking for a TypeScript declaration file, then this is a duplicate of #590. If not, then you've got a TypeScript issue not a d3fc issue.

As an aside, chasing issues with additional comments that don't provide additional context isn't helpful. The same goes for chasing maintainers directly by email.

**Closed as completed by chrisprice** 2021-02-20 20:02 UTC
