### ISSUE TITLE
donuts and gauge components would be a nice addition

### ISSUE THREAD

**Issue by markjose** [d3fc/d3fc#912] opened 2016-02-25 13:43 UTC

**Comment by ColinEberhardt** [comment] 2016-02-29 09:48
D3 itself has very good support for constructing pie / donut charts. Unless we can add some real innovation in this area, it's not something I'd want to prioritise.

For gauges, @oriondean is having a look at implementing a bullet chart - that's probably about as close to a gauge as we would want to get!

**Comment by chrisprice** [comment] 2018-08-20 15:51
Duplicate of #1085

**Closed by chrisprice** 2018-08-20 15:51 UTC
Labels: enhancement
