### ISSUE TITLE
Fix up workaround for web-gl Point

### ISSUE THREAD

**Issue by josted** [d3fc/d3fc#1421] opened 2020-01-31 10:28 UTC
Workaround added in https://github.com/d3fc/d3fc/pull/1407

We currently have two checks for: `if (verticesPerElement !== 1) {...}` in baseAttributeBuilder and programBuilder, which decide on the divisor and draw method for cases where verticesPerElement is 1 (as in Point).

Without these, Point will not render correctly. This issue aims to find a cleaner solution and to see what the potential interaction with
https://github.com/d3fc/d3fc/pull/1414 will be once it's merged.

**Comment by chrisprice** [comment] 2020-02-03 09:39
Duplicate of #1425

**Closed as completed by chrisprice** 2020-02-03 09:39 UTC
Labels: d3fc-webgl
