### ISSUE TITLE
Support rendering of labels in between ticks

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1153] opened 2018-08-09 15:36 UTC
_From @ColinEberhardt on April 4, 2017 14:13_

d3-axis doesn't support this, and it seems to be a popular request:

http://stackoverflow.com/questions/17544546/d3-js-align-text-labels-between-ticks-on-the-axis

_Copied from original issue: d3fc/d3fc-axis#14_

**Comment by chrisprice** [comment] 2018-08-22 16:11
Duplicate of #541

**Closed as completed by chrisprice** 2018-08-22 16:11 UTC
Labels: enhancement, d3fc-axis
